apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-limits-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-limits-service
  template:
    metadata:
      labels:
        app: payment-limits-service
    spec:
      containers:
        - name: payment-limits-service
          image: payment-limits-service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
