apiVersion: v1
kind: Service
metadata:
  name: payment-limits-service
  labels:
    backstage.io/kubernetes-id: payment-limits-service
spec:
  selector:
    app: payment-limits-service
  ports:
    - port: 80
      targetPort: 8080
